appid: "xxx"
secret: "xxx"
push_channel: "接受每日榜单推送的子频道id"
lib_path: "一般指Peeper-Board-Generator等第三方模块的父文件夹"
output_path: "生成的图片等文件的缓存路径"
clist_apikey: "ApiKey username:xxxxxxx"
uptime_apikey: "xxx"
admin_qq_id: ["管理员用户在群/频道的唯一标识符（并非qq号）"]
mod_qq_id: ["低权限管理员用户在群/频道的唯一标识符（并非qq号）"]
exclude_group_id: ["需要禁用Peeper-Board-Generator模块的群聊的唯一标识符（不是群号）"]
http_proxy: "除bot外的api请求/爬取网页走的http代理，不需要请留空"
https_proxy: "除bot外的api请求/爬取网页走的https代理，不需要请留空"